// Vocabulario completo - 4 cursos
// Cada entrada: { fr: 'francés', es: 'español', cat: 'subcategoría' }

window.VOCAB = {
  cotidiano: {
    id: 'cotidiano',
    name: 'Francés Día a Día',
    icon: '🥖',
    color: '#f59e0b',
    description: 'Vocabulario cotidiano para sobrevivir y conversar en Francia.',
    items: [
      { fr: "Bonjour", es: "Buenos días / Hola", cat: "Saludos" },
      { fr: "Bonsoir", es: "Buenas tardes/noches", cat: "Saludos" },
      { fr: "Salut", es: "Hola / Adiós (informal)", cat: "Saludos" },
      { fr: "Au revoir", es: "Adiós", cat: "Saludos" },
      { fr: "À bientôt", es: "Hasta pronto", cat: "Saludos" },
      { fr: "À demain", es: "Hasta mañana", cat: "Saludos" },
      { fr: "À plus", es: "Hasta luego", cat: "Saludos" },
      { fr: "Bonne nuit", es: "Buenas noches (dormir)", cat: "Saludos" },
      { fr: "Bonne journée", es: "Buen día", cat: "Saludos" },
      { fr: "Merci", es: "Gracias", cat: "Saludos" },
      { fr: "Merci beaucoup", es: "Muchas gracias", cat: "Saludos" },
      { fr: "De rien", es: "De nada", cat: "Saludos" },
      { fr: "Je vous en prie", es: "De nada (formal)", cat: "Saludos" },
      { fr: "S'il vous plaît", es: "Por favor (formal)", cat: "Saludos" },
      { fr: "S'il te plaît", es: "Por favor (informal)", cat: "Saludos" },
      { fr: "Excusez-moi", es: "Disculpe", cat: "Saludos" },
      { fr: "Pardon", es: "Perdón", cat: "Saludos" },
      { fr: "Comment ça va ?", es: "¿Cómo va?", cat: "Saludos" },
      { fr: "Ça va bien", es: "Bien", cat: "Saludos" },
      { fr: "Je m'appelle...", es: "Me llamo...", cat: "Presentación" },
      { fr: "Comment vous appelez-vous ?", es: "¿Cómo se llama?", cat: "Presentación" },
      { fr: "J'ai trente ans", es: "Tengo treinta años", cat: "Presentación" },
      { fr: "Je suis espagnol", es: "Soy español", cat: "Presentación" },
      { fr: "Je viens de Madrid", es: "Vengo de Madrid", cat: "Presentación" },
      { fr: "J'habite à...", es: "Vivo en...", cat: "Presentación" },
      { fr: "Je parle un peu français", es: "Hablo un poco de francés", cat: "Presentación" },
      { fr: "Enchanté", es: "Encantado", cat: "Presentación" },
      { fr: "un", es: "uno", cat: "Números" },
      { fr: "deux", es: "dos", cat: "Números" },
      { fr: "trois", es: "tres", cat: "Números" },
      { fr: "quatre", es: "cuatro", cat: "Números" },
      { fr: "cinq", es: "cinco", cat: "Números" },
      { fr: "six", es: "seis", cat: "Números" },
      { fr: "sept", es: "siete", cat: "Números" },
      { fr: "huit", es: "ocho", cat: "Números" },
      { fr: "neuf", es: "nueve", cat: "Números" },
      { fr: "dix", es: "diez", cat: "Números" },
      { fr: "vingt", es: "veinte", cat: "Números" },
      { fr: "trente", es: "treinta", cat: "Números" },
      { fr: "cinquante", es: "cincuenta", cat: "Números" },
      { fr: "soixante-dix", es: "setenta (60+10)", cat: "Números" },
      { fr: "quatre-vingts", es: "ochenta (4x20)", cat: "Números" },
      { fr: "cent", es: "cien", cat: "Números" },
      { fr: "mille", es: "mil", cat: "Números" },
      { fr: "Quelle heure est-il ?", es: "¿Qué hora es?", cat: "Tiempo" },
      { fr: "Il est huit heures", es: "Son las ocho", cat: "Tiempo" },
      { fr: "Il est midi", es: "Es mediodía", cat: "Tiempo" },
      { fr: "lundi", es: "lunes", cat: "Tiempo" },
      { fr: "mardi", es: "martes", cat: "Tiempo" },
      { fr: "mercredi", es: "miércoles", cat: "Tiempo" },
      { fr: "jeudi", es: "jueves", cat: "Tiempo" },
      { fr: "vendredi", es: "viernes", cat: "Tiempo" },
      { fr: "samedi", es: "sábado", cat: "Tiempo" },
      { fr: "dimanche", es: "domingo", cat: "Tiempo" },
      { fr: "aujourd'hui", es: "hoy", cat: "Tiempo" },
      { fr: "demain", es: "mañana", cat: "Tiempo" },
      { fr: "hier", es: "ayer", cat: "Tiempo" },
      { fr: "La famille", es: "La familia", cat: "Familia" },
      { fr: "Le père", es: "El padre", cat: "Familia" },
      { fr: "La mère", es: "La madre", cat: "Familia" },
      { fr: "Le frère", es: "El hermano", cat: "Familia" },
      { fr: "La sœur", es: "La hermana", cat: "Familia" },
      { fr: "Le fils", es: "El hijo", cat: "Familia" },
      { fr: "La fille", es: "La hija", cat: "Familia" },
      { fr: "Le mari", es: "El marido", cat: "Familia" },
      { fr: "La femme", es: "La mujer / esposa", cat: "Familia" },
      { fr: "Le grand-père", es: "El abuelo", cat: "Familia" },
      { fr: "La grand-mère", es: "La abuela", cat: "Familia" },
      { fr: "L'ami", es: "El amigo", cat: "Familia" },
      { fr: "Le café", es: "El café", cat: "Restaurante" },
      { fr: "Le restaurant", es: "El restaurante", cat: "Restaurante" },
      { fr: "La carte", es: "La carta", cat: "Restaurante" },
      { fr: "Le menu", es: "El menú", cat: "Restaurante" },
      { fr: "Le plat du jour", es: "El plato del día", cat: "Restaurante" },
      { fr: "L'addition", es: "La cuenta", cat: "Restaurante" },
      { fr: "Le pourboire", es: "La propina", cat: "Restaurante" },
      { fr: "L'eau", es: "El agua", cat: "Restaurante" },
      { fr: "Le vin", es: "El vino", cat: "Restaurante" },
      { fr: "Le pain", es: "El pan", cat: "Restaurante" },
      { fr: "Le fromage", es: "El queso", cat: "Restaurante" },
      { fr: "La viande", es: "La carne", cat: "Restaurante" },
      { fr: "Le poisson", es: "El pescado", cat: "Restaurante" },
      { fr: "Le petit-déjeuner", es: "El desayuno", cat: "Restaurante" },
      { fr: "Le déjeuner", es: "La comida", cat: "Restaurante" },
      { fr: "Le dîner", es: "La cena", cat: "Restaurante" },
      { fr: "Je voudrais...", es: "Quisiera...", cat: "Restaurante" },
      { fr: "Je vais prendre...", es: "Voy a tomar...", cat: "Restaurante" },
      { fr: "Sur place / à emporter", es: "Aquí / para llevar", cat: "Restaurante" },
      { fr: "Une table pour deux", es: "Una mesa para dos", cat: "Restaurante" },
      { fr: "Le magasin", es: "La tienda", cat: "Compras" },
      { fr: "Le supermarché", es: "El supermercado", cat: "Compras" },
      { fr: "La boulangerie", es: "La panadería", cat: "Compras" },
      { fr: "La pharmacie", es: "La farmacia", cat: "Compras" },
      { fr: "Le marché", es: "El mercado", cat: "Compras" },
      { fr: "La caisse", es: "La caja", cat: "Compras" },
      { fr: "L'argent", es: "El dinero", cat: "Compras" },
      { fr: "La carte bancaire", es: "La tarjeta", cat: "Compras" },
      { fr: "Les espèces", es: "El efectivo", cat: "Compras" },
      { fr: "Le prix", es: "El precio", cat: "Compras" },
      { fr: "Cher", es: "Caro", cat: "Compras" },
      { fr: "Pas cher", es: "Barato", cat: "Compras" },
      { fr: "Les soldes", es: "Las rebajas", cat: "Compras" },
      { fr: "La taille", es: "La talla", cat: "Compras" },
      { fr: "Combien ça coûte ?", es: "¿Cuánto cuesta?", cat: "Compras" },
      { fr: "C'est trop cher", es: "Es demasiado caro", cat: "Compras" },
      { fr: "Je peux essayer ?", es: "¿Puedo probar?", cat: "Compras" },
      { fr: "Je le prends", es: "Me lo llevo", cat: "Compras" },
      { fr: "La rue", es: "La calle", cat: "Direcciones" },
      { fr: "L'avenue", es: "La avenida", cat: "Direcciones" },
      { fr: "La place", es: "La plaza", cat: "Direcciones" },
      { fr: "À droite", es: "A la derecha", cat: "Direcciones" },
      { fr: "À gauche", es: "A la izquierda", cat: "Direcciones" },
      { fr: "Tout droit", es: "Todo recto", cat: "Direcciones" },
      { fr: "Près de", es: "Cerca de", cat: "Direcciones" },
      { fr: "Loin de", es: "Lejos de", cat: "Direcciones" },
      { fr: "En face de", es: "Enfrente de", cat: "Direcciones" },
      { fr: "Où est... ?", es: "¿Dónde está...?", cat: "Direcciones" },
      { fr: "Je suis perdu", es: "Estoy perdido", cat: "Direcciones" },
      { fr: "Le métro", es: "El metro", cat: "Transporte" },
      { fr: "Le bus", es: "El autobús", cat: "Transporte" },
      { fr: "Le train", es: "El tren", cat: "Transporte" },
      { fr: "Le taxi", es: "El taxi", cat: "Transporte" },
      { fr: "La voiture", es: "El coche", cat: "Transporte" },
      { fr: "La gare", es: "La estación", cat: "Transporte" },
      { fr: "Le billet", es: "El billete", cat: "Transporte" },
      { fr: "Aller-retour", es: "Ida y vuelta", cat: "Transporte" },
      { fr: "Aller simple", es: "Solo ida", cat: "Transporte" },
      { fr: "L'hôtel", es: "El hotel", cat: "Viajes" },
      { fr: "La chambre", es: "La habitación", cat: "Viajes" },
      { fr: "La clé", es: "La llave", cat: "Viajes" },
      { fr: "La réception", es: "La recepción", cat: "Viajes" },
      { fr: "La réservation", es: "La reserva", cat: "Viajes" },
      { fr: "L'aéroport", es: "El aeropuerto", cat: "Viajes" },
      { fr: "L'avion", es: "El avión", cat: "Viajes" },
      { fr: "La valise", es: "La maleta", cat: "Viajes" },
      { fr: "Le passeport", es: "El pasaporte", cat: "Viajes" },
      { fr: "Le médecin", es: "El médico", cat: "Salud" },
      { fr: "L'hôpital", es: "El hospital", cat: "Salud" },
      { fr: "La pharmacie", es: "La farmacia", cat: "Salud" },
      { fr: "Le médicament", es: "El medicamento", cat: "Salud" },
      { fr: "J'ai mal à la tête", es: "Me duele la cabeza", cat: "Salud" },
      { fr: "J'ai mal au ventre", es: "Me duele el estómago", cat: "Salud" },
      { fr: "J'ai de la fièvre", es: "Tengo fiebre", cat: "Salud" },
      { fr: "Je ne me sens pas bien", es: "No me siento bien", cat: "Salud" },
      { fr: "Au secours !", es: "¡Socorro!", cat: "Salud" },
      { fr: "Il fait beau", es: "Hace buen tiempo", cat: "Meteo" },
      { fr: "Il fait chaud", es: "Hace calor", cat: "Meteo" },
      { fr: "Il fait froid", es: "Hace frío", cat: "Meteo" },
      { fr: "Il pleut", es: "Llueve", cat: "Meteo" },
      { fr: "Il y a du soleil", es: "Hay sol", cat: "Meteo" },
      { fr: "Le ciel est nuageux", es: "El cielo está nublado", cat: "Meteo" },
      { fr: "J'aime...", es: "Me gusta...", cat: "Conversación" },
      { fr: "J'adore...", es: "Me encanta...", cat: "Conversación" },
      { fr: "Je déteste...", es: "Odio...", cat: "Conversación" },
      { fr: "C'est intéressant", es: "Es interesante", cat: "Conversación" },
      { fr: "Vraiment ?", es: "¿De verdad?", cat: "Conversación" },
      { fr: "Ah bon ?", es: "¿Ah sí?", cat: "Conversación" },
      { fr: "Je pense que...", es: "Creo que...", cat: "Conversación" },
      { fr: "Je suis d'accord", es: "Estoy de acuerdo", cat: "Conversación" },
      { fr: "Ça dépend", es: "Depende", cat: "Conversación" },
      { fr: "Bien sûr", es: "Por supuesto", cat: "Conversación" },
      { fr: "D'accord", es: "De acuerdo / vale", cat: "Conversación" },
      { fr: "Pas de problème", es: "No hay problema", cat: "Conversación" },
      { fr: "Avec plaisir", es: "Con mucho gusto", cat: "Conversación" },
      { fr: "Bonne idée !", es: "¡Buena idea!", cat: "Conversación" },
      { fr: "Pardon ?", es: "¿Perdón?", cat: "Comprensión" },
      { fr: "Pouvez-vous répéter ?", es: "¿Puede repetir?", cat: "Comprensión" },
      { fr: "Plus lentement", es: "Más despacio", cat: "Comprensión" },
      { fr: "Je ne comprends pas", es: "No entiendo", cat: "Comprensión" },
      { fr: "Qu'est-ce que ça veut dire ?", es: "¿Qué significa?", cat: "Comprensión" },
      { fr: "Comment ça s'écrit ?", es: "¿Cómo se escribe?", cat: "Comprensión" },
      { fr: "Je suis en train d'apprendre", es: "Estoy aprendiendo", cat: "Comprensión" }
    ]
  },

  it: {
    id: 'it',
    name: 'Francés IT Empresarial',
    icon: '💻',
    color: '#3b82f6',
    description: 'Vocabulario técnico de informática, soporte y empresa.',
    items: [
      { fr: "Bonjour", es: "Buenos días / Hola", cat: "Saludos" },
      { fr: "Bonsoir", es: "Buenas tardes/noches", cat: "Saludos" },
      { fr: "Au revoir", es: "Adiós", cat: "Saludos" },
      { fr: "À bientôt", es: "Hasta pronto", cat: "Saludos" },
      { fr: "Merci", es: "Gracias", cat: "Saludos" },
      { fr: "Merci beaucoup", es: "Muchas gracias", cat: "Saludos" },
      { fr: "De rien", es: "De nada", cat: "Saludos" },
      { fr: "S'il vous plaît", es: "Por favor (formal)", cat: "Saludos" },
      { fr: "Excusez-moi", es: "Disculpe", cat: "Saludos" },
      { fr: "Je m'appelle...", es: "Me llamo...", cat: "Presentación" },
      { fr: "Je suis technicien support IT", es: "Soy técnico de soporte IT", cat: "Presentación" },
      { fr: "Je travaille au service informatique", es: "Trabajo en el servicio informático", cat: "Presentación" },
      { fr: "Enchanté", es: "Encantado", cat: "Presentación" },
      { fr: "Comment ça va ?", es: "¿Cómo estás?", cat: "Presentación" },
      { fr: "L'ordinateur", es: "El ordenador", cat: "Hardware" },
      { fr: "L'ordinateur portable", es: "El portátil", cat: "Hardware" },
      { fr: "L'écran", es: "La pantalla", cat: "Hardware" },
      { fr: "Le clavier", es: "El teclado", cat: "Hardware" },
      { fr: "La souris", es: "El ratón", cat: "Hardware" },
      { fr: "L'imprimante", es: "La impresora", cat: "Hardware" },
      { fr: "Le disque dur", es: "El disco duro", cat: "Hardware" },
      { fr: "La mémoire", es: "La memoria RAM", cat: "Hardware" },
      { fr: "Le processeur", es: "El procesador", cat: "Hardware" },
      { fr: "La carte mère", es: "La placa base", cat: "Hardware" },
      { fr: "Le câble", es: "El cable", cat: "Hardware" },
      { fr: "Le chargeur", es: "El cargador", cat: "Hardware" },
      { fr: "Le casque", es: "Los auriculares", cat: "Hardware" },
      { fr: "Le micro", es: "El micrófono", cat: "Hardware" },
      { fr: "La webcam", es: "La webcam", cat: "Hardware" },
      { fr: "Le serveur", es: "El servidor", cat: "Hardware" },
      { fr: "Le routeur", es: "El router", cat: "Hardware" },
      { fr: "La batterie", es: "La batería", cat: "Hardware" },
      { fr: "Le logiciel", es: "El software / programa", cat: "Software" },
      { fr: "L'application", es: "La aplicación", cat: "Software" },
      { fr: "Le système d'exploitation", es: "El sistema operativo", cat: "Software" },
      { fr: "Le navigateur", es: "El navegador", cat: "Software" },
      { fr: "Le fichier", es: "El archivo", cat: "Software" },
      { fr: "Le dossier", es: "La carpeta", cat: "Software" },
      { fr: "Le document", es: "El documento", cat: "Software" },
      { fr: "La mise à jour", es: "La actualización", cat: "Software" },
      { fr: "L'installation", es: "La instalación", cat: "Software" },
      { fr: "La sauvegarde", es: "La copia de seguridad", cat: "Software" },
      { fr: "Le mot de passe", es: "La contraseña", cat: "Software" },
      { fr: "L'identifiant", es: "El nombre de usuario", cat: "Software" },
      { fr: "Le compte", es: "La cuenta", cat: "Software" },
      { fr: "Se connecter", es: "Iniciar sesión", cat: "Software" },
      { fr: "Se déconnecter", es: "Cerrar sesión", cat: "Software" },
      { fr: "Redémarrer", es: "Reiniciar", cat: "Software" },
      { fr: "Éteindre", es: "Apagar", cat: "Software" },
      { fr: "Allumer", es: "Encender", cat: "Software" },
      { fr: "Sauvegarder", es: "Guardar", cat: "Software" },
      { fr: "Supprimer", es: "Borrar / eliminar", cat: "Software" },
      { fr: "Télécharger", es: "Descargar", cat: "Software" },
      { fr: "Envoyer", es: "Enviar", cat: "Software" },
      { fr: "Le pare-feu", es: "El cortafuegos (firewall)", cat: "Software" },
      { fr: "L'antivirus", es: "El antivirus", cat: "Software" },
      { fr: "Le bug", es: "El error / bug", cat: "Software" },
      { fr: "La panne", es: "La avería", cat: "Software" },
      { fr: "Le réseau", es: "La red", cat: "Redes" },
      { fr: "La connexion", es: "La conexión", cat: "Redes" },
      { fr: "Le wifi", es: "El wifi", cat: "Redes" },
      { fr: "L'adresse IP", es: "La dirección IP", cat: "Redes" },
      { fr: "Le VPN", es: "La VPN", cat: "Redes" },
      { fr: "Le cloud", es: "La nube", cat: "Redes" },
      { fr: "Hors ligne", es: "Desconectado / offline", cat: "Redes" },
      { fr: "En ligne", es: "En línea / online", cat: "Redes" },
      { fr: "Le courriel", es: "El correo electrónico", cat: "Redes" },
      { fr: "La pièce jointe", es: "El archivo adjunto", cat: "Redes" },
      { fr: "La boîte de réception", es: "La bandeja de entrada", cat: "Redes" },
      { fr: "Le spam", es: "El spam", cat: "Redes" },
      { fr: "Un problème", es: "Un problema", cat: "Soporte" },
      { fr: "Une erreur", es: "Un error", cat: "Soporte" },
      { fr: "Le message d'erreur", es: "El mensaje de error", cat: "Soporte" },
      { fr: "Ne fonctionne pas", es: "No funciona", cat: "Soporte" },
      { fr: "Est bloqué", es: "Está bloqueado", cat: "Soporte" },
      { fr: "Est lent", es: "Está lento", cat: "Soporte" },
      { fr: "Plante", es: "Se cuelga", cat: "Soporte" },
      { fr: "L'écran bleu", es: "Pantalla azul", cat: "Soporte" },
      { fr: "Le redémarrage", es: "El reinicio", cat: "Soporte" },
      { fr: "La solution", es: "La solución", cat: "Soporte" },
      { fr: "Résoudre", es: "Resolver", cat: "Soporte" },
      { fr: "Réparer", es: "Reparar", cat: "Soporte" },
      { fr: "Vérifier", es: "Verificar / comprobar", cat: "Soporte" },
      { fr: "Tester", es: "Probar", cat: "Soporte" },
      { fr: "Le ticket", es: "El ticket / incidencia", cat: "Soporte" },
      { fr: "L'incident", es: "El incidente", cat: "Soporte" },
      { fr: "L'utilisateur", es: "El usuario", cat: "Soporte" },
      { fr: "Quel est le problème ?", es: "¿Cuál es el problema?", cat: "Frases" },
      { fr: "Pouvez-vous décrire le problème ?", es: "¿Puede describir el problema?", cat: "Frases" },
      { fr: "Depuis quand ?", es: "¿Desde cuándo?", cat: "Frases" },
      { fr: "Avez-vous essayé de redémarrer ?", es: "¿Ha intentado reiniciar?", cat: "Frases" },
      { fr: "Pouvez-vous me donner votre identifiant ?", es: "¿Puede darme su nombre de usuario?", cat: "Frases" },
      { fr: "Je vais vérifier", es: "Voy a comprobar", cat: "Frases" },
      { fr: "Un instant s'il vous plaît", es: "Un momento por favor", cat: "Frases" },
      { fr: "Je vais ouvrir un ticket", es: "Voy a abrir un ticket", cat: "Frases" },
      { fr: "Le problème est résolu", es: "El problema está resuelto", cat: "Frases" },
      { fr: "Pouvez-vous tester ?", es: "¿Puede probar?", cat: "Frases" },
      { fr: "Je transfère votre demande", es: "Transfiero su solicitud", cat: "Frases" },
      { fr: "Je reste à votre disposition", es: "Quedo a su disposición", cat: "Frases" },
      { fr: "Cordialement", es: "Atentamente", cat: "Email" },
      { fr: "Bien cordialement", es: "Atentamente (más cálido)", cat: "Email" },
      { fr: "Veuillez trouver ci-joint", es: "Adjunto encontrará", cat: "Email" },
      { fr: "J'ai bien reçu votre message", es: "He recibido bien su mensaje", cat: "Email" },
      { fr: "Pourriez-vous me préciser... ?", es: "¿Podría precisarme...?", cat: "Email" },
      { fr: "Suite à votre demande", es: "Tras su solicitud", cat: "Email" },
      { fr: "N'hésitez pas à me contacter", es: "No dude en contactarme", cat: "Email" },
      { fr: "Comment puis-je vous aider ?", es: "¿En qué puedo ayudarle?", cat: "Llamada" },
      { fr: "Pouvez-vous patienter ?", es: "¿Puede esperar?", cat: "Llamada" },
      { fr: "Je vous mets en attente", es: "Le pongo en espera", cat: "Llamada" },
      { fr: "Je vous rappelle", es: "Le devuelvo la llamada", cat: "Llamada" },
      { fr: "Pouvez-vous répéter ?", es: "¿Puede repetir?", cat: "Llamada" },
      { fr: "Pouvez-vous parler plus lentement ?", es: "¿Puede hablar más despacio?", cat: "Llamada" },
      { fr: "Pouvez-vous épeler ?", es: "¿Puede deletrear?", cat: "Llamada" },
      { fr: "Je suis en train d'apprendre le français", es: "Estoy aprendiendo francés", cat: "Llamada" },
      { fr: "L'entreprise", es: "La empresa", cat: "Oficina" },
      { fr: "Le bureau", es: "La oficina / El escritorio", cat: "Oficina" },
      { fr: "Le collègue", es: "El compañero de trabajo", cat: "Oficina" },
      { fr: "Le chef", es: "El jefe", cat: "Oficina" },
      { fr: "L'équipe", es: "El equipo", cat: "Oficina" },
      { fr: "La réunion", es: "La reunión", cat: "Oficina" },
      { fr: "Le projet", es: "El proyecto", cat: "Oficina" },
      { fr: "Le client", es: "El cliente", cat: "Oficina" },
      { fr: "Le télétravail", es: "El teletrabajo", cat: "Oficina" },
      { fr: "La visioconférence", es: "La videoconferencia", cat: "Oficina" },
      { fr: "Le rendez-vous", es: "La cita", cat: "Oficina" }
    ]
  },

  marketing: {
    id: 'marketing',
    name: 'Francés Marketing Inmobiliario',
    icon: '🏘️',
    color: '#10b981',
    description: 'Vocabulario de marketing y sector inmobiliario.',
    items: [
      { fr: "L'immobilier", es: "El sector inmobiliario", cat: "General" },
      { fr: "L'agence immobilière", es: "La agencia inmobiliaria", cat: "General" },
      { fr: "L'agent immobilier", es: "El agente inmobiliario", cat: "General" },
      { fr: "Le bien immobilier", es: "El bien inmueble", cat: "General" },
      { fr: "Le propriétaire", es: "El propietario", cat: "General" },
      { fr: "L'acheteur", es: "El comprador", cat: "General" },
      { fr: "Le vendeur", es: "El vendedor", cat: "General" },
      { fr: "Le locataire", es: "El inquilino", cat: "General" },
      { fr: "Le bailleur", es: "El arrendador", cat: "General" },
      { fr: "L'acquéreur", es: "El adquirente", cat: "General" },
      { fr: "Le mandat", es: "El mandato / contrato con agencia", cat: "General" },
      { fr: "La commission", es: "La comisión", cat: "General" },
      { fr: "Les honoraires", es: "Los honorarios", cat: "General" },
      { fr: "L'achat", es: "La compra", cat: "General" },
      { fr: "La vente", es: "La venta", cat: "General" },
      { fr: "La location", es: "El alquiler", cat: "General" },
      { fr: "Le notaire", es: "El notario", cat: "General" },
      { fr: "Le compromis de vente", es: "El precontrato de venta", cat: "General" },
      { fr: "L'estimation", es: "La tasación", cat: "General" },
      { fr: "Le loyer", es: "El alquiler mensual", cat: "General" },
      { fr: "La caution", es: "La fianza", cat: "General" },
      { fr: "Le bail", es: "El contrato de alquiler", cat: "General" },
      { fr: "L'appartement", es: "El piso", cat: "Propiedades" },
      { fr: "La maison", es: "La casa", cat: "Propiedades" },
      { fr: "Le studio", es: "El estudio", cat: "Propiedades" },
      { fr: "Le T2 / F2", es: "Apartamento 1 dormitorio", cat: "Propiedades" },
      { fr: "Le T3 / F3", es: "Apartamento 2 dormitorios", cat: "Propiedades" },
      { fr: "Le duplex", es: "El dúplex", cat: "Propiedades" },
      { fr: "Le loft", es: "El loft", cat: "Propiedades" },
      { fr: "La villa", es: "El chalet", cat: "Propiedades" },
      { fr: "Le château", es: "El castillo / palacete", cat: "Propiedades" },
      { fr: "L'hôtel particulier", es: "El palacete urbano", cat: "Propiedades" },
      { fr: "L'immeuble", es: "El edificio", cat: "Propiedades" },
      { fr: "Le terrain", es: "El terreno", cat: "Propiedades" },
      { fr: "Le local commercial", es: "El local comercial", cat: "Propiedades" },
      { fr: "Lumineux", es: "Luminoso", cat: "Características" },
      { fr: "Spacieux", es: "Espacioso", cat: "Características" },
      { fr: "Calme", es: "Tranquilo", cat: "Características" },
      { fr: "Refait à neuf", es: "Reformado", cat: "Características" },
      { fr: "Rénové", es: "Renovado", cat: "Características" },
      { fr: "Avec cachet", es: "Con encanto", cat: "Características" },
      { fr: "Coup de cœur", es: "Flechazo", cat: "Características" },
      { fr: "Vue dégagée", es: "Vista despejada", cat: "Características" },
      { fr: "Plein sud", es: "Orientación sur", cat: "Características" },
      { fr: "Traversant", es: "Pasante", cat: "Características" },
      { fr: "Haut de gamme", es: "De gama alta", cat: "Características" },
      { fr: "Idéalement situé", es: "Idealmente ubicado", cat: "Características" },
      { fr: "Atypique", es: "Atípico", cat: "Características" },
      { fr: "Le salon", es: "El salón", cat: "Espacios" },
      { fr: "La cuisine équipée", es: "La cocina equipada", cat: "Espacios" },
      { fr: "La chambre", es: "El dormitorio", cat: "Espacios" },
      { fr: "La salle de bain", es: "El baño", cat: "Espacios" },
      { fr: "Le balcon", es: "El balcón", cat: "Espacios" },
      { fr: "La terrasse", es: "La terraza", cat: "Espacios" },
      { fr: "Le jardin", es: "El jardín", cat: "Espacios" },
      { fr: "La cave", es: "El sótano / bodega", cat: "Espacios" },
      { fr: "Le parking", es: "El parking", cat: "Espacios" },
      { fr: "L'ascenseur", es: "El ascensor", cat: "Espacios" },
      { fr: "La piscine", es: "La piscina", cat: "Espacios" },
      { fr: "Le marketing", es: "El marketing", cat: "Marketing" },
      { fr: "La communication", es: "La comunicación", cat: "Marketing" },
      { fr: "La publicité", es: "La publicidad", cat: "Marketing" },
      { fr: "La campagne", es: "La campaña", cat: "Marketing" },
      { fr: "La stratégie", es: "La estrategia", cat: "Marketing" },
      { fr: "La cible", es: "El público objetivo", cat: "Marketing" },
      { fr: "Les réseaux sociaux", es: "Las redes sociales", cat: "Marketing" },
      { fr: "L'audience", es: "La audiencia", cat: "Marketing" },
      { fr: "L'engagement", es: "El engagement", cat: "Marketing" },
      { fr: "La notoriété", es: "La notoriedad", cat: "Marketing" },
      { fr: "L'image de marque", es: "La imagen de marca", cat: "Marketing" },
      { fr: "Le référencement", es: "El SEO", cat: "Marketing" },
      { fr: "Le site web", es: "La página web", cat: "Marketing" },
      { fr: "Le contenu", es: "El contenido", cat: "Marketing" },
      { fr: "La publication", es: "La publicación", cat: "Marketing" },
      { fr: "L'abonné", es: "El follower / suscriptor", cat: "Marketing" },
      { fr: "Le taux de conversion", es: "La tasa de conversión", cat: "Marketing" },
      { fr: "Le ROI", es: "El ROI / retorno", cat: "Marketing" },
      { fr: "La visite virtuelle", es: "La visita virtual", cat: "Marketing" },
      { fr: "La photo professionnelle", es: "La foto profesional", cat: "Marketing" },
      { fr: "La marque", es: "La marca", cat: "Branding" },
      { fr: "Le logo", es: "El logo", cat: "Branding" },
      { fr: "La charte graphique", es: "La identidad visual", cat: "Branding" },
      { fr: "Le slogan", es: "El eslogan", cat: "Branding" },
      { fr: "Le positionnement", es: "El posicionamiento", cat: "Branding" },
      { fr: "Les valeurs", es: "Los valores", cat: "Branding" },
      { fr: "La promesse", es: "La promesa de marca", cat: "Branding" },
      { fr: "Le storytelling", es: "El storytelling", cat: "Branding" },
      { fr: "Le persona", es: "El buyer persona", cat: "Branding" },
      { fr: "L'étude de marché", es: "El estudio de mercado", cat: "Datos" },
      { fr: "La tendance", es: "La tendencia", cat: "Datos" },
      { fr: "L'offre et la demande", es: "La oferta y la demanda", cat: "Datos" },
      { fr: "Le prix au mètre carré", es: "El precio por m²", cat: "Datos" },
      { fr: "La hausse", es: "El alza", cat: "Datos" },
      { fr: "La baisse", es: "La bajada", cat: "Datos" },
      { fr: "Augmenter", es: "Aumentar", cat: "Datos" },
      { fr: "Diminuer", es: "Disminuir", cat: "Datos" },
      { fr: "Le pourcentage", es: "El porcentaje", cat: "Datos" },
      { fr: "Les statistiques", es: "Las estadísticas", cat: "Datos" },
      { fr: "Le KPI", es: "El KPI", cat: "Datos" },
      { fr: "Le rapport", es: "El informe", cat: "Datos" },
      { fr: "Le délai de vente", es: "El plazo de venta", cat: "Datos" },
      { fr: "Le prospect", es: "El prospecto / lead", cat: "Ventas" },
      { fr: "Le lead", es: "El lead", cat: "Ventas" },
      { fr: "Le client potentiel", es: "El cliente potencial", cat: "Ventas" },
      { fr: "La prospection", es: "La prospección", cat: "Ventas" },
      { fr: "La négociation", es: "La negociación", cat: "Ventas" },
      { fr: "L'offre", es: "La oferta", cat: "Ventas" },
      { fr: "La contre-offre", es: "La contraoferta", cat: "Ventas" },
      { fr: "Le devis", es: "El presupuesto", cat: "Ventas" },
      { fr: "La promesse de vente", es: "La promesa de venta", cat: "Ventas" },
      { fr: "L'apport personnel", es: "La aportación personal", cat: "Ventas" },
      { fr: "Le crédit immobilier", es: "La hipoteca", cat: "Ventas" },
      { fr: "Le taux d'intérêt", es: "La tasa de interés", cat: "Ventas" },
      { fr: "La rentabilité", es: "La rentabilidad", cat: "Ventas" },
      { fr: "Le rendement", es: "El rendimiento", cat: "Ventas" },
      { fr: "La newsletter", es: "La newsletter", cat: "Email" },
      { fr: "L'objet de l'email", es: "El asunto", cat: "Email" },
      { fr: "Le destinataire", es: "El destinatario", cat: "Email" },
      { fr: "La liste de diffusion", es: "La lista de difusión", cat: "Email" },
      { fr: "Le taux d'ouverture", es: "La tasa de apertura", cat: "Email" },
      { fr: "Le taux de clic", es: "La tasa de clic", cat: "Email" },
      { fr: "L'appel à l'action", es: "La llamada a la acción / CTA", cat: "Email" },
      { fr: "Cordialement", es: "Atentamente", cat: "Email" },
      { fr: "Bien à vous", es: "Cordialmente", cat: "Email" },
      { fr: "Le salon professionnel", es: "La feria profesional", cat: "Eventos" },
      { fr: "Le stand", es: "El stand", cat: "Eventos" },
      { fr: "L'événement", es: "El evento", cat: "Eventos" },
      { fr: "La porte ouverte", es: "Las puertas abiertas", cat: "Eventos" },
      { fr: "Le partenariat", es: "La colaboración", cat: "Eventos" },
      { fr: "Le partenaire", es: "El socio", cat: "Eventos" },
      { fr: "Le réseautage", es: "El networking", cat: "Eventos" },
      { fr: "La carte de visite", es: "La tarjeta de visita", cat: "Eventos" },
      { fr: "La conférence", es: "La conferencia", cat: "Eventos" },
      { fr: "Coup de cœur garanti", es: "Flechazo garantizado", cat: "Frases" },
      { fr: "À deux pas de...", es: "A dos pasos de...", cat: "Frases" },
      { fr: "Bien rare sur le marché", es: "Bien raro en el mercado", cat: "Frases" },
      { fr: "Idéal premier achat", es: "Ideal primera compra", cat: "Frases" },
      { fr: "Parfait pour investisseur", es: "Perfecto para inversor", cat: "Frases" },
      { fr: "Honoraires charge vendeur", es: "Honorarios paga el vendedor", cat: "Frases" },
      { fr: "Visite virtuelle sur demande", es: "Visita virtual bajo petición", cat: "Frases" },
      { fr: "Notre stratégie porte ses fruits", es: "Nuestra estrategia da frutos", cat: "Frases" },
      { fr: "Le rapport qualité-prix est imbattable", es: "Calidad-precio imbatible", cat: "Frases" },
      { fr: "C'est une excellente opportunité", es: "Es una excelente oportunidad", cat: "Frases" }
    ]
  },

  secretaria: {
    id: 'secretaria',
    name: 'Francés Secretaría Inmobiliaria',
    icon: '📞',
    color: '#ec4899',
    description: 'Vocabulario administrativo, teléfono, recepción y citas.',
    items: [
      { fr: "Bonjour", es: "Buenos días", cat: "Saludos" },
      { fr: "Bonsoir", es: "Buenas tardes", cat: "Saludos" },
      { fr: "Madame", es: "Señora", cat: "Saludos" },
      { fr: "Monsieur", es: "Señor", cat: "Saludos" },
      { fr: "Au revoir", es: "Adiós", cat: "Saludos" },
      { fr: "Bonne journée", es: "Buen día", cat: "Saludos" },
      { fr: "Bonne fin de journée", es: "Buen final del día", cat: "Saludos" },
      { fr: "Bon week-end", es: "Buen fin de semana", cat: "Saludos" },
      { fr: "Merci", es: "Gracias", cat: "Saludos" },
      { fr: "Je vous en prie", es: "De nada (formal)", cat: "Saludos" },
      { fr: "S'il vous plaît", es: "Por favor", cat: "Saludos" },
      { fr: "Excusez-moi", es: "Disculpe", cat: "Saludos" },
      { fr: "Enchanté(e)", es: "Encantado(a)", cat: "Saludos" },
      { fr: "L'agent immobilier", es: "El agente inmobiliario", cat: "Personas" },
      { fr: "Le consultant", es: "El consultor", cat: "Personas" },
      { fr: "Le directeur d'agence", es: "El director de la agencia", cat: "Personas" },
      { fr: "Le propriétaire", es: "El propietario", cat: "Personas" },
      { fr: "L'acheteur", es: "El comprador", cat: "Personas" },
      { fr: "Le vendeur", es: "El vendedor", cat: "Personas" },
      { fr: "Le locataire", es: "El inquilino", cat: "Personas" },
      { fr: "Le bailleur", es: "El arrendador", cat: "Personas" },
      { fr: "Le notaire", es: "El notario", cat: "Personas" },
      { fr: "Un appartement", es: "Un piso", cat: "Propiedades" },
      { fr: "Une maison", es: "Una casa", cat: "Propiedades" },
      { fr: "Un studio", es: "Un estudio", cat: "Propiedades" },
      { fr: "Un T2", es: "1 dormitorio", cat: "Propiedades" },
      { fr: "Un T3", es: "2 dormitorios", cat: "Propiedades" },
      { fr: "Une villa", es: "Un chalet", cat: "Propiedades" },
      { fr: "L'achat", es: "La compra", cat: "Operaciones" },
      { fr: "La vente", es: "La venta", cat: "Operaciones" },
      { fr: "La location", es: "El alquiler", cat: "Operaciones" },
      { fr: "La visite", es: "La visita", cat: "Operaciones" },
      { fr: "L'estimation", es: "La tasación", cat: "Operaciones" },
      { fr: "Le mandat", es: "El mandato", cat: "Operaciones" },
      { fr: "Le compromis de vente", es: "El precontrato", cat: "Operaciones" },
      { fr: "Le bail", es: "El contrato de alquiler", cat: "Operaciones" },
      { fr: "L'état des lieux", es: "El acta de entrega", cat: "Operaciones" },
      { fr: "La caution", es: "La fianza", cat: "Operaciones" },
      { fr: "Le dépôt de garantie", es: "El depósito", cat: "Operaciones" },
      { fr: "Comment puis-je vous aider ?", es: "¿En qué puedo ayudarle?", cat: "Teléfono" },
      { fr: "Ruben à l'appareil", es: "Ruben al habla", cat: "Teléfono" },
      { fr: "C'est de la part de qui ?", es: "¿De parte de quién?", cat: "Teléfono" },
      { fr: "Quel est votre nom ?", es: "¿Cuál es su nombre?", cat: "Teléfono" },
      { fr: "Pouvez-vous épeler ?", es: "¿Puede deletrear?", cat: "Teléfono" },
      { fr: "Un instant s'il vous plaît", es: "Un momento por favor", cat: "Teléfono" },
      { fr: "Je vérifie", es: "Lo verifico", cat: "Teléfono" },
      { fr: "Je vous mets en attente", es: "Le pongo en espera", cat: "Teléfono" },
      { fr: "Ne quittez pas", es: "No cuelgue", cat: "Teléfono" },
      { fr: "Je vous passe...", es: "Le paso con...", cat: "Teléfono" },
      { fr: "Je vais vous transférer", es: "Le voy a transferir", cat: "Teléfono" },
      { fr: "Puis-je prendre un message ?", es: "¿Puedo tomar un mensaje?", cat: "Teléfono" },
      { fr: "Il vous rappellera", es: "Le llamará de vuelta", cat: "Teléfono" },
      { fr: "Pouvez-vous répéter ?", es: "¿Puede repetir?", cat: "Teléfono" },
      { fr: "La ligne est mauvaise", es: "La línea está mala", cat: "Teléfono" },
      { fr: "Je vous remercie de votre appel", es: "Le agradezco su llamada", cat: "Teléfono" },
      { fr: "L'accueil", es: "La recepción", cat: "Recepción" },
      { fr: "Le visiteur", es: "El visitante", cat: "Recepción" },
      { fr: "La salle d'attente", es: "La sala de espera", cat: "Recepción" },
      { fr: "La salle de réunion", es: "La sala de reuniones", cat: "Recepción" },
      { fr: "Le bureau", es: "El despacho", cat: "Recepción" },
      { fr: "Bienvenue à l'agence", es: "Bienvenido a la agencia", cat: "Recepción" },
      { fr: "Vous avez rendez-vous avec qui ?", es: "¿Con quién tiene cita?", cat: "Recepción" },
      { fr: "Veuillez patienter", es: "Espere por favor", cat: "Recepción" },
      { fr: "Asseyez-vous", es: "Siéntese", cat: "Recepción" },
      { fr: "Installez-vous", es: "Póngase cómodo", cat: "Recepción" },
      { fr: "Puis-je vous offrir un café ?", es: "¿Le ofrezco un café?", cat: "Recepción" },
      { fr: "Avec du sucre ?", es: "¿Con azúcar?", cat: "Recepción" },
      { fr: "Suivez-moi s'il vous plaît", es: "Sígame por favor", cat: "Recepción" },
      { fr: "Je vous accompagne", es: "Le acompaño", cat: "Recepción" },
      { fr: "L'agenda", es: "La agenda", cat: "Citas" },
      { fr: "Le rendez-vous", es: "La cita", cat: "Citas" },
      { fr: "La disponibilité", es: "La disponibilidad", cat: "Citas" },
      { fr: "Disponible", es: "Disponible", cat: "Citas" },
      { fr: "Libre", es: "Libre", cat: "Citas" },
      { fr: "Occupé", es: "Ocupado", cat: "Citas" },
      { fr: "Quelles sont vos disponibilités ?", es: "¿Cuál es su disponibilidad?", cat: "Citas" },
      { fr: "Êtes-vous libre cette semaine ?", es: "¿Está libre esta semana?", cat: "Citas" },
      { fr: "Je vous propose lundi à 14h", es: "Le propongo lunes a las 14h", cat: "Citas" },
      { fr: "Cela vous convient ?", es: "¿Le viene bien?", cat: "Citas" },
      { fr: "C'est noté", es: "Apuntado", cat: "Citas" },
      { fr: "Reporter le rendez-vous", es: "Aplazar la cita", cat: "Citas" },
      { fr: "Annuler", es: "Anular", cat: "Citas" },
      { fr: "Décaler", es: "Mover", cat: "Citas" },
      { fr: "Confirmation par email", es: "Confirmación por email", cat: "Citas" },
      { fr: "Bonjour Madame Dupont,", es: "Buenos días Sra. Dupont,", cat: "Email" },
      { fr: "Madame Monsieur,", es: "Estimados,", cat: "Email" },
      { fr: "Je me permets de vous contacter", es: "Me permito contactarle", cat: "Email" },
      { fr: "Suite à notre conversation", es: "Tras nuestra conversación", cat: "Email" },
      { fr: "Veuillez trouver ci-joint", es: "Adjunto encontrará", cat: "Email" },
      { fr: "N'hésitez pas à me contacter", es: "No dude en contactarme", cat: "Email" },
      { fr: "Cordialement", es: "Atentamente", cat: "Email" },
      { fr: "Bien cordialement", es: "Atentamente (cálido)", cat: "Email" },
      { fr: "Dans l'attente de votre retour", es: "A la espera de su respuesta", cat: "Email" },
      { fr: "Restant à votre disposition", es: "Quedando a su disposición", cat: "Email" },
      { fr: "Le document", es: "El documento", cat: "Documentos" },
      { fr: "Le dossier", es: "El expediente", cat: "Documentos" },
      { fr: "Le contrat", es: "El contrato", cat: "Documentos" },
      { fr: "L'attestation", es: "El certificado", cat: "Documentos" },
      { fr: "Le justificatif", es: "El justificante", cat: "Documentos" },
      { fr: "La pièce d'identité", es: "El documento de identidad", cat: "Documentos" },
      { fr: "Le RIB", es: "El número de cuenta", cat: "Documentos" },
      { fr: "L'avis d'imposition", es: "La declaración de impuestos", cat: "Documentos" },
      { fr: "Le bulletin de salaire", es: "La nómina", cat: "Documentos" },
      { fr: "La signature", es: "La firma", cat: "Documentos" },
      { fr: "La copie", es: "La copia", cat: "Documentos" },
      { fr: "L'original", es: "El original", cat: "Documentos" },
      { fr: "La réunion d'équipe", es: "La reunión de equipo", cat: "Equipo" },
      { fr: "L'urgence", es: "La urgencia", cat: "Equipo" },
      { fr: "La priorité", es: "La prioridad", cat: "Equipo" },
      { fr: "La tâche", es: "La tarea", cat: "Equipo" },
      { fr: "Le délai", es: "El plazo", cat: "Equipo" },
      { fr: "Vous avez un client à l'accueil", es: "Tiene un cliente en recepción", cat: "Equipo" },
      { fr: "J'ai un appel pour vous", es: "Tengo una llamada para usted", cat: "Equipo" },
      { fr: "Vous avez rendez-vous dans 10 minutes", es: "Tiene cita en 10 minutos", cat: "Equipo" },
      { fr: "Je comprends votre frustration", es: "Entiendo su frustración", cat: "Quejas" },
      { fr: "Je suis vraiment désolé", es: "Lo siento mucho", cat: "Quejas" },
      { fr: "Je vous prie de nous excuser", es: "Le ruego que nos disculpe", cat: "Quejas" },
      { fr: "Je vous écoute attentivement", es: "Le escucho atentamente", cat: "Quejas" },
      { fr: "Nous allons trouver une solution", es: "Vamos a encontrar una solución", cat: "Quejas" },
      { fr: "Je m'engage à...", es: "Me comprometo a...", cat: "Quejas" },
      { fr: "Permettez-moi de vérifier", es: "Permítame verificar", cat: "Quejas" },
      { fr: "La facture", es: "La factura", cat: "Administrativo" },
      { fr: "Le devis", es: "El presupuesto", cat: "Administrativo" },
      { fr: "Le paiement", es: "El pago", cat: "Administrativo" },
      { fr: "Le virement", es: "La transferencia", cat: "Administrativo" },
      { fr: "La carte bancaire", es: "La tarjeta", cat: "Administrativo" },
      { fr: "Les espèces", es: "El efectivo", cat: "Administrativo" },
      { fr: "La TVA", es: "El IVA", cat: "Administrativo" },
      { fr: "Le montant", es: "El importe", cat: "Administrativo" },
      { fr: "L'acompte", es: "El anticipo", cat: "Administrativo" },
      { fr: "La quittance de loyer", es: "El recibo de alquiler", cat: "Administrativo" },
      { fr: "L'échéance", es: "El vencimiento", cat: "Administrativo" },
      { fr: "Le rappel", es: "El recordatorio", cat: "Administrativo" },
      { fr: "La relance", es: "El aviso de impago", cat: "Administrativo" },
      { fr: "Le fournisseur", es: "El proveedor", cat: "Administrativo" },
      { fr: "Les fournitures de bureau", es: "El material de oficina", cat: "Administrativo" }
    ]
  }
};

// Pre-calcular un ID estable por entrada para SRS y orden de cursos
(function init() {
  window.COURSE_ORDER = ['cotidiano', 'it', 'marketing', 'secretaria'];
  Object.values(window.VOCAB).forEach(course => {
    course.items.forEach((item, idx) => {
      item.id = course.id + ':' + idx;
      item.courseId = course.id;
    });
  });
})();
